FROM node:18
# Setup working directory
WORKDIR /app
# Copy package.json to working directory
COPY package.json ./
# Install npm dependencies optimized for production
RUN npm install
# Copy current directory to the container working directory
COPY . .
# Expose
EXPOSE 3000
# Run startup command
CMD ["npm", "run", "dev"]